# Generated by Django 5.0.6 on 2024-07-02 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_id_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.movie', to_field='title'),
        ),
    ]
