# Generated by Django 5.0.6 on 2024-07-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_show_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='hallno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hall', to_field='number'),
        ),
        migrations.AlterField(
            model_name='show',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hall', to_field='number'),
        ),
    ]
